### ISSUE TITLE
Not indent correctly HTML

### ISSUE THREAD

**Issue by iBobik** [socsieng/IndentX#11] opened 2015-11-19 07:40 UTC
Issue with command: Indent

Sample input:

```
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="https://ovacopi.us10.list-manage.com/subscribe/post?u=5ecd9de4c3c0820ab682489ce&amp;id=d06b6f42bf" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="mc-field-group">
	<label for="mce-EMAIL">E-mail<span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">Jméno</label>
	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Příjmení</label>
	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_5ecd9de4c3c0820ab682489ce_d06b6f42bf" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
```

Given result:

```
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
	<form action="https://ovacopi.us10.list-manage.com/subscribe/post?u=5ecd9de4c3c0820ab682489ce&amp;id=d06b6f42bf" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
		<div id="mc_embed_signup_scroll">
			<div class="mc-field-group">
				<label for="mce-EMAIL">E-mail
					<span class="asterisk">*</span>
				</label>
				<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL"></div>
				<div class="mc-field-group">
					<label for="mce-FNAME">Jméno</label>
					<input type="text" value="" name="FNAME" class="" id="mce-FNAME"></div>
					<div class="mc-field-group">
						<label for="mce-LNAME">Příjmení</label>
						<input type="text" value="" name="LNAME" class="" id="mce-LNAME"></div>
						<div id="mce-responses" class="clear">
							<div class="response" id="mce-error-response" style="display:none"></div>
							<div class="response" id="mce-success-response" style="display:none"></div>
						</div>
						<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups -->
						<div style="position: absolute; left: -5000px;" aria-hidden="true">
							<input type="text" name="b_5ecd9de4c3c0820ab682489ce_d06b6f42bf" tabindex="-1" value=""></div>
							<div class="clear">
								<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
							</div>
						</form>
					</div>
					<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script>
					<script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
					<!-- End mc_embed_signup -->
```

Expected result:

```
<div id="mc_embed_signup">
	<form action="https://ovacopi.us10.list-manage.com/subscribe/post?u=5ecd9de4c3c0820ab682489ce&amp;id=d06b6f42bf" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	    <div id="mc_embed_signup_scroll">
		
			<div class="mc-field-group">
				<label for="mce-EMAIL">
					E-mail<span class="asterisk">*</span>
				</label>
				<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
			</div>
			<div class="mc-field-group">
				<label for="mce-FNAME">Jméno</label>
				<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
			</div>
			<div class="mc-field-group">
				<label for="mce-LNAME">Příjmení</label>
				<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
			</div>
			<div id="mce-responses" class="clear">
				<div class="response" id="mce-error-response" style="display:none"></div>
				<div class="response" id="mce-success-response" style="display:none"></div>
			</div>
			<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
		    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_5ecd9de4c3c0820ab682489ce_d06b6f42bf" tabindex="-1" value=""></div>
		    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
	    </div>
	</form>
</div>
```

**Comment by socsieng** [comment] 2015-11-19 10:17
Hi @iBobik, it looks like the issue is that the `input` tags are not closed or self-closing. This utility is geared more towards XML than it is HTML. While this is something I might look implementing further down the track, it's not something that will be implemented in the near future.

Work-around for the time being is to close the `input` tags. Example:

```
<!-- from this -->
<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">

<!-- to this -->
<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" />
```

**Closed** 2015-11-19 22:25 UTC
